version: '3'
networks:
    frontend:
      driver: bridge
services:
  apache:
    image: psychemedics/apache:7.2
    container_name: psycho-apache-teste
    volumes:
    - ./${APLICATION_LARAVEL_NAME}:/var/www/html/
    ports:
    - "8001:8080"
    networks:
      - frontend
  node:
    image: psychemedics/node:10.0
    container_name: psycho-node-teste
    volumes:
    - ./${APLICATION_ANGULAR_NAME}:/usr/src/app/
    command:
      ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - frontend
